site_name: cyyz-wiki
site_url: https://electrowind.github.io/cyyz-wiki
theme:
  language: 'zh'
  name: material
  palette:
    accent: green
    primary: white
  logo: images/cyyz.bmp
  features:
    - search.highlight
  plugins:
    - search
  favicon: images/cyyz.bmp

markdown_extensions:
   - pymdownx.arithmatex:
       generic: true
   - pymdownx.betterem

nav:
  - Home:
    - Index: index.md
    - 前言: intro/Pre-saying.md
    - 鸣谢: intro/thanks.md
    - 加入我们: intro/joinus.md
  - 食堂: 
    - 前言: dish/index.md
    - 特色区: 
      - 简介 & 目录 : dish/special/menu.md
      - 面条: dish/special/noodles.md
      - 粉丝: dish/special/starchnoodles.md
      - 米线: dish/special/ricenoodles.md
      - 馄饨: dish/special/wonton.md
      - 肉夹馍: dish/special/roujiamo.md
      - 卷饼: dish/special/burritos.md
      - 盖浇饭: dish/special/rice-with-toppings.md
      - 烤肠: dish/special/sausage.md
    - 打饭区: dish/diningarea.md
    - 杂类: dish/others.md
  - 尚未分类:
    - 宣誓词: unclassfied/affidavit.md

extra_css:
  - stylesheets/extra.css
