site_name: cyyz-wiki
site_url: https://electrowind.github.io/cyyz-wiki
theme:
  language: 'zh'
  name: material
  palette:
    scheme: nthing
    primary: white
    accent: green
  logo: images/icon.png
  features:
    - search.highlight
    - navigation.instant
    - navigation.tabs
    # - navigation.footer
    - content.action.edit
    - content.action.view
  favicon: images/icon.png  

repo_url: https://github.com/electrowind/cyyz-wiki
repo_name: electrowind/cyyz-wiki
edit_uri: edit/main/docs/

plugins:
  - search
  - blog:
      authors_profiles: true
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
#   - social
  

markdown_extensions:
   - pymdownx.arithmatex:
       generic: true
   - pymdownx.betterem

nav:
  - Home:
    - Index: index.md
    - 前言: intro/Pre-saying.md
    - 鸣谢: intro/thanks.md
    - 加入我们: intro/joinus.md
  - 食堂: 
    - 前言: dish/index.md
    - 早餐: dish/breakfast.md
    - 特色区: 
      - 简介 & 目录 : dish/special/menu.md
      - 面条: dish/special/noodles.md
      - 粉丝: dish/special/starchnoodles.md
      - 米线: dish/special/ricenoodles.md
      - 馄饨: dish/special/wonton.md
      - 肉夹馍: dish/special/roujiamo.md
      - 卷饼: dish/special/burritos.md
      - 盖浇饭: dish/special/rice-with-toppings.md
      - 烤肠: dish/special/sausage.md
    - 打饭区: dish/diningarea.md
    - 杂类: dish/others.md
  - 校园:
    - 前言: campus/index.md
    - 教学楼: campus/teaching-building.md
    - 操场: campus/playground.md
    - 食堂: campus/dinninghall.md
    - 雕塑: campus/sculpture.md
    - 天问楼，体育馆与学术报告厅: campus/tianwen-gym-and-hall.md
    - 宿舍: campus/dorm.md
    - 其他: campus/others.md
  - 教师: teachers.md
  - 尚未分类:
    - 宣誓词: unclassfied/affidavit.md
    - 诗作: unclassfied/poem.md
    - ??? : unclassfied/test.md
  - Blog:
    - blog/index.md

extra_css:
  - stylesheets/extra.css
